### ISSUE TITLE
eks使用第二天后无信息

### ISSUE THREAD

**Issue by ksmiracle** [kubefin/kubefin#15]
## What version of kubefin?

> v0.1.0

## Expected Behavior

查看相应的namespace的成本核算

## Actual Behavior

在安装第二天后,我没有进行任何修改,在访问dashboad时无法获取到任何数据

## Steps to Reproduce the Problem

我在eks的1.26版本 没有进行任何的操作,在更新到v0.1.1后恢复了正常,我会持续帮助观察

**Comment by mrhello369** [comment]
Thanks for trying, I will try to reproduce it in my local env.

**Comment by mrhello369** [comment]
After set the memory requests higher, this problem doesn't exists anymore.
