### ISSUE TITLE
bug: prometheus metric未清理导致出现多余计费账单

### ISSUE THREAD

**Issue by leonharetd** [kubefin/kubefin#29]
## In what area(s)?

> /area agent

## What version of kubefin?
latest

## Expected Behavior
pod 完成后，账单停止计费。

## Actual Behavior
pod 完成后，账单还会进行计费

## Steps to Reproduce the Problem

启动一个job，job结束后看是否继续计费

**Comment by leonharetd** [comment]
https://github.com/kubefin/kubefin/blob/fef2a53746dc4eb116c97f2305acdc4e992a3db9/pkg/metrics/core/pod_metrics.go#L142
这里如果pod结束，没有把该pod从metric里删除，prometheus下次pull的时候还会将上次的值收回。

**Comment by mrhello369** [comment]
This issue is fixed, let's close it.
