### ISSUE TITLE
多集群部署

### ISSUE THREAD

**Issue by xinmans** [kubefin/kubefin#40]
多k8s集群如何部署agent上报到一个kubefin-cost-analyzer里并展现

**Comment by mrhello369** [comment]
Hi, @xinmans 

I will provider a document about how to do it soon.

I will notify you once it's ready. If you want to try it, you can clone the repo and run:
```sh
hack/local-start-kubefin.sh
``

**Comment by oliviershrek** [comment]
# how to add a new cluster to kubefin

1. ensure that the metrics-server is running.

```shell
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
```

2. download the latest kubefin repo

```shell 
# hack/init_secondary_config.sh <CLUSTER_PROVIDER> <CLUSTER_NAME> <METRICS_WRITE_ADDRESS>, for example: 
hack/init-secondary-config.sh default cluster-2 http://127.0.0.1:2345/api/v1/push

# change image to kubefin/kubefin-agent
vim config_secondary/core/deployments/kubefin-agent.yaml
```

3. apply

```shell
kubectl apply -Rf config_secondary
```

**Comment by mrhello369** [comment]
Hi, @xinmans 
The installation method is described in https://www.kubefin.dev/docs/installation/multi-cluster-installation/

Feel free to open a new issue if you meet any problems.
