### ISSUE TITLE
doc: Update repo readme to adopt to the newest installation method

### ISSUE THREAD

**Issue by mrhello369** [kubefin/kubefin#59]
/kind doc

## Expected Behavior
After PR: https://github.com/kubefin/kubefin/pull/56
We need to adopt to the newest installation method in repo readme

## Actual Behavior
none

## Steps to Reproduce the Problem
none

## Additional Info
website also needs it.

**Comment by REestrella** [comment]
The script is done. But maybe need to wait after next release. After that, users can install kubefin without downloading codes and with one simple command.

**Comment by mrhello369** [comment]
Finished in https://github.com/kubefin/kubefin/pull/102
Close this issue
