### ISSUE TITLE
Change namespace kubefin to kubefin-system

### ISSUE THREAD

**Issue by REestrella** [kubefin/kubefin#65]
Seems most of project put their component in XXX-system namespace. Do we need to update kubefin to kubefin-system?

**Comment by mrhello369** [comment]
I check istio, it's installed in istio-system.

So I think would be better if we install in kubefin-system namespace

**Comment by mrhello369** [comment]
Could you assist with this, @REestrella? 
We ought to incorporate this into v0.2.0.
